# Generated by Django 5.1.4 on 2025-05-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
