# Generated by Django 5.1.4 on 2025-05-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='paragraph',
            new_name='paragra',
        ),
    ]
