# Generated by Django 5.1.4 on 2025-05-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_paragra_about_content_remove_about_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
