# Generated by Django 5.1.4 on 2025-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='About Factual Vibes', max_length=200),
            preserve_default=False,
        ),
    ]
